### ISSUE TITLE
Slit Flap strange Behaviour

### ISSUE THREAD

**Issue by daniele8808** [jp112sdl/SplitFlap#2]
Hello Jerome, I saw your project and it's seem working very well. I've also tried to make my display using the ScottBez1 file but I'm having some problem displaying the correct character inside my module. I wrote to Scott but maybe it's to busy to help me so I'm wondering if you had the same problems I'm having and if you can help me to solve is.
I have completed the construction of a module and mechanically it should be ok, I have also done some tests with the sensor and it is correctly detected but I still cannot see the letter I want on my display. In this short video I show the three problems I'm having:

https://youtu.be/BHOUhOT_epA (this video was made for Scott but explain which are my problems)

1 error: often when I select a letter to view the display freezes after 2 steps for no reason
2 error: if I try to display a character that is too far from the starting point (for example I switch from A to Z), the display makes a complete revolution and returns to A, but no errors are reported on the console
3 error: a few times when I recalibrate by entering the @ the display arrives at the home point and adds a micro step that changes the initial letter

I would be really grateful if you could help me complete this project.
Thanks in advance

Daniele

**Comment by jp112sdl** [comment]
Hi and sorry for the late reply.

It's been a long time ago since working on my splitflap so... I hope I can help you

1.) Can be a bad power supply?

2+3) Are you using my code from here: https://github.com/jp112sdl/SplitFlap/blob/master/Code/SplitFlap/SplitFlap.ino ?
_I don't know, how the Scott's code is working; i wrote my own_

I have declared an offset `ZERO_OFFSET_DEFAULTS`:
https://github.com/jp112sdl/SplitFlap/blob/a9b46231fd3726ffb9cbe177fb51e2d02c6dcdb5/Code/SplitFlap/SplitFlap.ino#L15

The position, where the magnet reaches the hall sensor, is nearly on the **last** flap.
Then I added some steps (`ZERO_OFFSET_DEFAULTS`) that let the last flap fall to the the first flap.

**Comment by daniele8808** [comment]
Hello Jerome,
Thanks for the answer, I still managed to solve my problem by doing some debugging. The problem was with the cards not moving well and for this reason the engine was trying too hard and I was unable to display the letters I wanted. However, I thank you anyway for your availability.

Daniele
